import { ArrowLeft, Building2, Check, ChevronDown, FileUp, Plus, Save, X } from 'lucide-react'
import { ChangeEvent, FormEvent, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { PageHeader } from '../shared/ui/PageHeader'

type Requisites = { shortName: string; fullName: string; address: string; department: string; phone: string }
type ApplicationForm = { receivedDate: string; number: string; signedDate: string; faculties: string[] }
type OrderRow = { id: number; faculty: string; specialty: string; qualification: string; values: Record<number, number> }
const years = Array.from({ length: 11 }, (_, index) => 2026 + index)
const faculties = ['Машиностроительный', 'Механико-технологический', 'Автотракторный', 'Маркетинга, менеджмента, предпринимательства', 'Строительный', 'Горного дела и инженерной экологии']
const initialRows: OrderRow[] = [
  { id: 1, faculty: 'Машиностроительный', specialty: '1-36 01 03 02', qualification: 'Инженер', values: { 2026: 2 } },
  { id: 2, faculty: 'Механико-технологический', specialty: '1-42 01 01-01 03', qualification: 'Инженер', values: { 2026: 3 } },
  { id: 3, faculty: 'Автотракторный', specialty: '1-27 01 01-02', qualification: 'Инженер-экономист', values: {} },
  { id: 4, faculty: 'Маркетинга, менеджмента, предпринимательства', specialty: '1-25 01 07', qualification: 'Экономист-менеджер', values: { 2026: 3 } },
  { id: 5, faculty: 'Автотракторный', specialty: '1-37 01 03', qualification: 'Инженер-механик', values: { 2026: 15, 2027: 16 } },
  { id: 6, faculty: 'Автотракторный', specialty: '1-36 01 07', qualification: 'Инженер-механик', values: { 2026: 1, 2027: 1 } },
]
const initialRequisites: Requisites = { shortName: 'ОАО «МТЗ»', fullName: 'Открытое акционерное общество "Минский тракторный завод"', address: 'ул. Долгобродская, 29, 220070, г. Минск', department: 'Министерство промышленности', phone: '' }

export function OrganizationPage() {
  const { id } = useParams()
  const [rows, setRows] = useState(initialRows)
  const [requisites, setRequisites] = useState(initialRequisites)
  const [editedRequisites, setEditedRequisites] = useState(initialRequisites)
  const [isRequisitesOpen, setRequisitesOpen] = useState(false)
  const [selectedFaculties, setSelectedFaculties] = useState<string[]>([])
  const [contractNumber, setContractNumber] = useState('')
  const [contractDate, setContractDate] = useState('')
  const [scanName, setScanName] = useState('')
  const [status, setStatus] = useState('Активен')
  const [isApplicationOpen, setApplicationOpen] = useState(false)
  const [application, setApplication] = useState<ApplicationForm>({ receivedDate: '', number: '', signedDate: '', faculties: [] })
  const [applicationSaved, setApplicationSaved] = useState(false)

  const openRequisites = () => { setEditedRequisites(requisites); setRequisitesOpen(true) }
  const saveRequisites = (event: FormEvent) => { event.preventDefault(); setRequisites(editedRequisites); setRequisitesOpen(false) }
  const updateRequisite = (field: keyof Requisites, value: string) => setEditedRequisites(current => ({ ...current, [field]: value }))
  const addRow = () => setRows(current => [...current, { id: Date.now(), faculty: faculties[0], specialty: '', qualification: '', values: {} }])
  const removeRow = (rowId: number) => setRows(current => current.filter(row => row.id !== rowId))
  const updateRow = (rowId: number, field: 'faculty' | 'specialty' | 'qualification', value: string) => setRows(current => current.map(row => row.id === rowId ? { ...row, [field]: value } : row))
  const updateValue = (rowId: number, year: number, value: string) => setRows(current => current.map(row => row.id === rowId ? { ...row, values: { ...row.values, [year]: Number(value) || 0 } } : row))
  const toggleFaculty = (faculty: string) => setSelectedFaculties(current => current.includes(faculty) ? current.filter(item => item !== faculty) : [...current, faculty])
  const selectScan = (event: ChangeEvent<HTMLInputElement>) => setScanName(event.target.files?.[0]?.name ?? '')
  const updateApplication = (field: keyof Omit<ApplicationForm, 'faculties'>, value: string) => setApplication(current => ({ ...current, [field]: value }))
  const toggleApplicationFaculty = (faculty: string) => setApplication(current => ({ ...current, faculties: current.faculties.includes(faculty) ? current.faculties.filter(item => item !== faculty) : [...current.faculties, faculty] }))
  const saveApplication = (event: FormEvent) => { event.preventDefault(); setApplicationSaved(true); setApplicationOpen(false); window.setTimeout(() => setApplicationSaved(false), 2500) }

  return <>
    <Link className="back-link" to="/"><ArrowLeft size={16} /> К реестру</Link>
    <PageHeader eyebrow={`ОРГАНИЗАЦИЯ · #${id}`} title={requisites.shortName} description={requisites.fullName} action={<><button className="secondary" type="button" onClick={() => setApplicationOpen(true)}><Plus size={14} /> Зарегистрировать заявку</button>{isApplicationOpen && <ApplicationModal2 application={application} organizationName={requisites.shortName} onChange={setApplication} onClose={() => setApplicationOpen(false)} onSave={saveApplication} />}</>} />
    <div className="organization-top-grid">
      <section className="organization-card requisites-card"><h3><Building2 size={15} /> Реквизиты</h3><dl><div><dt>Адрес</dt><dd>{requisites.address}</dd></div><div><dt>Ведомство</dt><dd>{requisites.department}</dd></div><div><dt>Телефоны</dt><dd>{requisites.phone || '—'}</dd></div></dl><button className="requisites-button" type="button" onClick={openRequisites}>Редактировать реквизиты</button></section>
      <section className="organization-card add-contract-card"><h3>Добавить договор</h3><label>Факультеты<div className="faculty-picker"><button type="button" onClick={() => setSelectedFaculties(selectedFaculties.length ? [] : faculties.slice(0, 3))}>Выберите факультеты <ChevronDown size={13} /></button>{selectedFaculties.length > 0 && <div className="faculty-options">{faculties.map(faculty => <label key={faculty}><input type="checkbox" checked={selectedFaculties.includes(faculty)} onChange={() => toggleFaculty(faculty)} /> {faculty}</label>)}</div>}</div></label><div className="contract-fields"><input placeholder="Номер договора" value={contractNumber} onChange={event => setContractNumber(event.target.value)} /><input type="date" value={contractDate} onChange={event => setContractDate(event.target.value)} /><button className="primary" type="button" onClick={() => setContractNumber('')}>Добавить</button></div></section>
    </div>
    <section className="contract-panel"><div className="contract-heading"><div><h2>Договор д.с. №1 от 06.05.2025 №221-АТФ/280 от 01.10.2020</h2><p>Машиностроительный, Механико-технологический, Автотракторный · <span className="status-pill">{status}</span> · срок до <b>31.12.2030</b></p></div><div className="contract-actions"><button className="secondary" type="button" onClick={() => setStatus(status === 'Активен' ? 'На проверке' : 'Активен')}>Сменить статус</button><button className="primary" type="button"><FileUp size={14} /> Сформировать доп. соглашение</button></div></div><div className="contract-links"><button className="inline-link" type="button">▸ Редактировать договор</button><button className="inline-link" type="button">+ Зарегистрировать дополнительное соглашение</button></div><div className="order-table-wrap"><table className="order-table"><thead><tr><th>Факультет</th><th>Специальность</th><th>Квалификация</th>{years.map(year => <th key={year}>{year}</th>)}<th /></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><select value={row.faculty} onChange={event => updateRow(row.id, 'faculty', event.target.value)}>{faculties.map(faculty => <option key={faculty}>{faculty}</option>)}</select></td><td><input value={row.specialty} onChange={event => updateRow(row.id, 'specialty', event.target.value)} /></td><td><input value={row.qualification} onChange={event => updateRow(row.id, 'qualification', event.target.value)} /></td>{years.map(year => <td key={year}><input className="year-input" type="number" min="0" value={row.values[year] ?? 0} onChange={event => updateValue(row.id, year, event.target.value)} /></td>)}<td><div className="row-actions"><button className="row-confirm" type="button" title="Сохранить строку"><Check size={15} /></button><button className="row-delete" type="button" title="Удалить строку" onClick={() => removeRow(row.id)}><X size={14} /></button></div></td></tr>)}</tbody></table></div><button className="inline-link add-row" type="button" onClick={addRow}>▸ + Добавить строку заказа</button><div className="scan-footer"><b>Сканы подписанных документов:</b><span>{scanName || 'не загружены'}</span><label className="secondary attach-button"><FileUp size={14} /> Прикрепить скан<input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={selectScan} hidden /></label></div></section>
    {isRequisitesOpen && <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setRequisitesOpen(false) }}><form className="requisites-modal" onSubmit={saveRequisites}><div className="modal-header"><div><div className="eyebrow">РЕКВИЗИТЫ ОРГАНИЗАЦИИ</div><h2>Редактировать реквизиты</h2><p>Обновите данные организации-заказчика.</p></div><button className="icon-button" type="button" aria-label="Закрыть" onClick={() => setRequisitesOpen(false)}><X size={18} /></button></div><div className="requisites-modal-fields"><label>Краткое наименование<input value={editedRequisites.shortName} onChange={event => updateRequisite('shortName', event.target.value)} required /></label><label>Полное наименование<input value={editedRequisites.fullName} onChange={event => updateRequisite('fullName', event.target.value)} required /></label><label>Адрес<input value={editedRequisites.address} onChange={event => updateRequisite('address', event.target.value)} required /></label><label>Ведомство<input value={editedRequisites.department} onChange={event => updateRequisite('department', event.target.value)} /></label><label>Телефон<input value={editedRequisites.phone} onChange={event => updateRequisite('phone', event.target.value)} /></label></div><div className="modal-actions"><button className="secondary" type="button" onClick={() => setRequisitesOpen(false)}>Отмена</button><button className="primary" type="submit"><Save size={15} /> Сохранить</button></div></form></div>}
  </>
}

function ApplicationModal({ application, organizationName, onChange, onClose, onSave }: { application: ApplicationForm; organizationName: string; onChange: (value: ApplicationForm) => void; onClose: () => void; onSave: (event: FormEvent) => void }) {
  const update = (field: keyof Omit<ApplicationForm, 'faculties'>, value: string) => onChange({ ...application, [field]: value })
  const toggleFaculty = (faculty: string) => onChange({ ...application, faculties: application.faculties.includes(faculty) ? application.faculties.filter(item => item !== faculty) : [...application.faculties, faculty] })
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><form className="application-modal" onSubmit={onSave}><div className="modal-header"><div><h2>Зарегистрировать заявку</h2><p>{organizationName} · заявка уже получена от организации</p></div><button className="icon-button" type="button" aria-label="Закрыть" onClick={onClose}><X size={18} /></button></div><div className="application-modal-fields"><label>Дата получения<input type="date" value={application.receivedDate} onChange={event => update('receivedDate', event.target.value)} required /></label><label>Номер заявки<input value={application.number} onChange={event => update('number', event.target.value)} required /></label><label>Дата подписания<input type="date" value={application.signedDate} onChange={event => update('signedDate', event.target.value)} /></label><label>Факультеты по специальностям<div className="application-faculties">{faculties.map(faculty => <label key={faculty}><input type="checkbox" checked={application.faculties.includes(faculty)} onChange={() => toggleFaculty(faculty)} /> {faculty}</label>)}</div></label></div><div className="modal-actions"><button className="secondary" type="button" onClick={onClose}>Отмена</button><button className="primary" type="submit">Зарегистрировать заявку</button></div></form></div>
}

function ApplicationModal2({ application, organizationName, onChange, onClose, onSave }: { application: ApplicationForm; organizationName: string; onChange: (value: ApplicationForm) => void; onClose: () => void; onSave: (event: FormEvent) => void }) {
  const [isFacultyOpen, setFacultyOpen] = useState(false)
  const [facultyQuery, setFacultyQuery] = useState('')
  const filteredFaculties = faculties.filter(faculty => faculty.toLowerCase().includes(facultyQuery.toLowerCase()))
  const toggleFaculty = (faculty: string) => onChange({ ...application, faculties: application.faculties.includes(faculty) ? application.faculties.filter(item => item !== faculty) : [...application.faculties, faculty] })
  const update = (field: keyof Omit<ApplicationForm, 'faculties'>, value: string) => onChange({ ...application, [field]: value })
  return <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><form className="application-modal" onSubmit={onSave}><div className="modal-header"><div><h2>Зарегистрировать заявку</h2><p>{organizationName} · заявка уже получена от организации</p></div><button className="icon-button" type="button" aria-label="Закрыть" onClick={onClose}><X size={18} /></button></div><div className="application-modal-fields"><label>Дата получения<input type="date" value={application.receivedDate} onChange={event => update('receivedDate', event.target.value)} required /></label><label>Номер заявки<input value={application.number} onChange={event => update('number', event.target.value)} required /></label><label>Дата подписания<input type="date" value={application.signedDate} onChange={event => update('signedDate', event.target.value)} /></label><label>Факультеты по специальностям<div className="faculty-multiselect"><button className="faculty-select-trigger" type="button" onClick={() => setFacultyOpen(current => !current)}>Выберите факультеты <ChevronDown size={13} /></button>{isFacultyOpen && <div className="faculty-dropdown"><input className="faculty-dropdown-search" autoFocus placeholder="Поиск факультета" value={facultyQuery} onChange={event => setFacultyQuery(event.target.value)} /> <div className="faculty-dropdown-list">{filteredFaculties.map(faculty => <label key={faculty}><input type="checkbox" checked={application.faculties.includes(faculty)} onChange={() => toggleFaculty(faculty)} /> <span>{faculty}</span></label>)}</div></div>}</div></label></div><div className="modal-actions"><button className="secondary" type="button" onClick={onClose}>Отмена</button><button className="primary" type="submit">Зарегистрировать заявку</button></div></form></div>
}
