import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import { App } from './app/App'
import { Providers } from './app/providers'
import './styles.css'
import './login.css'
import './transfer.css'
import './users.css'
import './select.css'
import './user-actions.css'
import './delete-modal.css'
import './settings.css'
import './organizations.css'
import './app-shell.css'
import './organization-detail.css'
import './organization-modal.css'
import './application-modal.css'

createRoot(document.getElementById('root')!).render(<StrictMode><BrowserRouter><Providers><App /></Providers></BrowserRouter></StrictMode>)
